<?
usleep(23000);
?>
<h1>The BAR page</h1>

<p>
This is a page about BAR. 
I think BAR is the best part of FOO BAR. 
Don't you agree?
</p>

<p>
Would you like to go back to the <a href="index.php">front page</a>?
</p>

<p>
Also, for some reason, here is quite a lot of text. 
2709 words, or 18048 bytes, of Lorem Ipsum, to be exact.
</p>

<hr/>

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec aliquet tincidunt orci, ut ultricies orci malesuada sit amet. Nam at nulla nibh. Praesent placerat, enim sed ultricies dignissim, urna risus facilisis magna, quis eleifend est ipsum blandit nibh. Vestibulum mollis sapien quis ipsum dapibus a aliquam tortor iaculis. Proin nisi ligula, condimentum eget lobortis et, luctus ut mauris. Mauris dui purus, lacinia eget venenatis et, viverra sed risus. Aliquam pulvinar malesuada eros in vehicula.

Phasellus ac purus non nibh rhoncus mollis lacinia sed lectus. Curabitur lectus nisl, lacinia eu sagittis vitae, rhoncus ut tortor. Phasellus justo felis, gravida ut porta fringilla, malesuada id turpis. In dapibus fringilla odio nec suscipit. Suspendisse aliquet ipsum eu libero semper in malesuada est tincidunt. Etiam condimentum tincidunt nisi, a vehicula leo varius vel. Pellentesque elementum libero eu ligula pretium eu semper diam posuere. Ut commodo bibendum nisl in viverra. Morbi semper, leo nec rhoncus interdum, enim nisi malesuada arcu, id auctor enim turpis in massa. Proin elementum congue ligula, ut ultricies odio euismod eget.

Ut volutpat suscipit lobortis. Vestibulum ut gravida justo. Vivamus vitae consequat lorem. Donec vitae enim odio, et faucibus nisl. Suspendisse a dui molestie est sagittis ultricies. Cras luctus volutpat arcu, egestas tincidunt orci vulputate porttitor. Nullam lorem neque, posuere eget venenatis a, consectetur eu mi. Morbi malesuada, sapien id gravida sollicitudin, diam lacus tincidunt ante, vel bibendum massa diam a libero. Morbi ullamcorper congue dolor vitae semper.

Maecenas sit amet purus eu arcu tempus iaculis nec interdum magna. Nulla diam urna, placerat sed sagittis non, vehicula sed massa. Nam ut metus at lectus lobortis ullamcorper. Sed pharetra dictum rhoncus. Phasellus ut magna vitae orci accumsan hendrerit eget in augue. Duis mi nisi, ullamcorper et dignissim sit amet, varius sed odio. Donec eu ultricies velit.

Sed quis est nec ante mattis pellentesque. Cras viverra sodales nunc in tempus. Integer ultricies dignissim quam eu venenatis. Vivamus dapibus orci non velit fermentum in interdum nibh molestie. Donec sagittis volutpat leo eu interdum. Nunc ac sapien id augue volutpat tempor. Sed porttitor consectetur posuere. Aenean aliquet augue a arcu venenatis sed commodo magna adipiscing. Phasellus rhoncus blandit quam a tempor.

Etiam aliquet est augue, a tempor ante. Donec id elit neque, nec gravida massa. Vivamus nec nunc sem, ut tempor libero. Donec blandit consequat sem, ut lacinia leo pretium in. Nunc in magna id sapien tincidunt ornare. In mi tortor, eleifend eget ultricies sit amet, lobortis quis leo. Nam suscipit lacus vel mi venenatis eget malesuada ligula scelerisque. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Suspendisse mollis placerat leo et hendrerit. Mauris malesuada, massa vitae convallis adipiscing, tellus eros ultrices eros, vel lobortis dolor eros interdum nisi. In hac habitasse platea dictumst. Suspendisse a nibh magna. Etiam mollis, diam nec suscipit pellentesque, ante massa varius enim, eget euismod nisi mi ut arcu. Morbi volutpat ullamcorper diam, ut tincidunt tellus congue id. Integer faucibus convallis est, at aliquet quam feugiat in.

In urna lectus, pharetra nec dignissim non, tempor ac massa. Mauris orci dolor, facilisis non porttitor in, dapibus eget mi. Nulla auctor ipsum nec velit feugiat convallis. Mauris ultrices, felis ut facilisis imperdiet, est felis ullamcorper dui, varius convallis nisi libero id tortor. Praesent lobortis egestas leo, id euismod purus feugiat eu. Vestibulum fermentum congue est, in vehicula elit ultrices sit amet. Donec rhoncus odio ac erat pulvinar vel auctor tellus tristique. Praesent quis metus ipsum. Nullam at orci lacus, vel tincidunt mi. Nunc tristique aliquam ante, id accumsan libero venenatis a. Vivamus sit amet leo hendrerit leo aliquet fringilla. Etiam ultricies magna ac urna eleifend nec posuere diam scelerisque. Praesent in risus diam, vitae vehicula lorem.

Sed nisi magna, mollis sed porttitor ut, porttitor at odio. Maecenas auctor, dui non ultrices mollis, ipsum massa dignissim turpis, eu faucibus massa sapien sed sem. Vestibulum fringilla nunc interdum tellus consectetur sed luctus dui elementum. Vivamus ultrices, risus ut imperdiet tempor, dolor leo viverra mi, eu feugiat velit turpis non quam. Donec ac ante erat, vitae dictum diam. Nullam facilisis, erat at varius posuere, lectus nibh ultrices ante, sit amet tincidunt ligula mauris sit amet tortor. Ut nec tristique magna. Proin et felis ut quam ullamcorper mollis. Etiam eu lorem libero.

Proin et ipsum et magna placerat semper vitae vitae orci. Nunc at arcu eros. Aenean tempus hendrerit neque, quis fermentum ligula rutrum non. Vestibulum orci dolor, pulvinar ut facilisis eget, bibendum ac est. Morbi rutrum ultrices venenatis. Donec aliquam varius ipsum, sit amet egestas nisi suscipit sed. Donec pretium iaculis erat id commodo.

Sed sed arcu ligula, ut congue orci. Fusce ac neque magna, sed consequat nulla. Ut ut urna at enim suscipit varius eu sed neque. Quisque vitae nisi nunc. Ut ullamcorper lacus id diam venenatis at semper erat pellentesque. Aenean posuere mi sed risus condimentum pellentesque. Nunc ornare ante at tortor feugiat eu porta nulla tincidunt. Donec sed nunc nunc. Suspendisse ante tortor, porttitor vel convallis volutpat, gravida nec velit. Vestibulum turpis magna, accumsan eu gravida quis, aliquam ut lacus. Sed varius, leo eu lacinia placerat, augue enim blandit metus, vel gravida sem sapien eget nibh. Etiam ante ipsum, porta rutrum pharetra at, facilisis sed lacus. Nam aliquam lacus nec urna suscipit eleifend.

Mauris purus est, consectetur nec fringilla vel, sagittis id tellus. Donec tristique venenatis purus, eu suscipit nulla lacinia nec. Pellentesque dolor ligula, eleifend sed pharetra vel, dictum at neque. In interdum accumsan luctus. Nulla sed ultricies metus. Aenean mauris odio, facilisis nec dictum eget, venenatis quis nunc. Mauris est tellus, condimentum eget fermentum ut, lacinia eu turpis. Aliquam aliquam nunc sit amet lacus dictum dapibus.

Curabitur dapibus consectetur lectus, in consectetur justo tempor ac. Vestibulum vitae consectetur urna. Fusce sit amet lacus tortor, pharetra egestas nunc. Pellentesque at hendrerit purus. Quisque laoreet nunc vitae nisi interdum in tristique dui aliquet. Phasellus vel massa a sem imperdiet lobortis vel eget erat. Aenean rutrum lobortis pellentesque. Fusce non ultrices orci. In eget leo sit amet enim adipiscing vulputate sed quis mi. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi nec leo vitae tellus ultrices lacinia et et urna. Nulla eros urna, tempus eu facilisis vel, tempus vel nulla. Nullam et sem est, id ultricies est. Duis ut tortor et augue pretium dictum. Maecenas interdum laoreet nunc ut dignissim. Proin sed massa id est semper porttitor in et libero.

Donec pellentesque sagittis arcu, eget fringilla est vehicula placerat. Vivamus eleifend porta augue tempor sollicitudin. Etiam placerat orci eget ante tincidunt nec feugiat mauris condimentum. Cras at odio odio, nec euismod enim. Sed turpis sapien, molestie eget sagittis a, posuere ac velit. Praesent sagittis, diam ut posuere elementum, nulla felis semper magna, sed commodo nibh lacus ut elit. Integer nec lacus id sapien hendrerit consectetur. Nullam sem mauris, iaculis elementum malesuada at, imperdiet non elit. Suspendisse pellentesque, diam sed sodales bibendum, urna dui venenatis libero, nec ultrices nulla leo ut leo. Aenean vulputate feugiat imperdiet. Etiam commodo faucibus vulputate. Maecenas eu sodales metus.

Aliquam in diam nec eros dignissim accumsan id rutrum turpis. Aliquam feugiat sagittis feugiat. Vivamus ultrices metus nec orci ultrices condimentum. Morbi quis dignissim enim. Aenean volutpat elementum erat ac facilisis. Nunc dapibus risus eget tortor sollicitudin eget condimentum erat fermentum. Donec quis neque at dui gravida mollis. Nulla quis diam magna. Nullam ac leo odio. Praesent posuere dignissim porta. Aliquam vitae fringilla elit. Aenean ultrices, nibh ut tempus pharetra, eros nibh ultricies justo, id consequat diam neque vel velit. Etiam eleifend vehicula dui, vitae euismod libero dapibus vel. Mauris at ligula tempor orci convallis facilisis non dapibus elit. Vivamus placerat sem et nisl rutrum sagittis.

Ut porta, lorem vel hendrerit porta, turpis dui volutpat enim, dictum hendrerit augue justo sed purus. Nullam nec pulvinar ipsum. Donec vehicula pretium mattis. Vivamus in metus tortor. Proin vel sollicitudin urna. Proin diam dui, posuere in iaculis ac, hendrerit condimentum nibh. Vestibulum euismod semper nulla, quis congue elit tempor ut. Sed ligula nibh, mattis eget vehicula et, lacinia quis massa. Donec quis ante augue. Curabitur et hendrerit augue. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin leo ante, hendrerit a sollicitudin sed, lobortis ut erat. Donec at ante lacus, ut semper leo. Aenean hendrerit, ipsum non fringilla facilisis, quam eros ultrices lorem, eu interdum odio sem et orci.

Pellentesque non lectus ipsum, quis consectetur lorem. Maecenas cursus felis ac erat accumsan ac lacinia metus sodales. Nulla sit amet orci quam, in sodales tellus. Vestibulum hendrerit tincidunt vulputate. Nam dapibus nunc vitae nunc accumsan non tincidunt sem accumsan. Nullam nunc elit, vehicula et sodales ut, malesuada at tellus. Mauris fermentum lobortis sodales. Phasellus nec facilisis ipsum.

Nullam sodales rhoncus dui egestas fermentum. Suspendisse ac tempor lorem. Mauris porttitor enim id nulla eleifend fringilla. Maecenas quis est neque. Nunc mattis ultrices nisl, eget eleifend leo ullamcorper et. Fusce vel sapien sit amet ligula vestibulum aliquam vitae in tortor. Duis tincidunt laoreet tempus. Donec nec imperdiet ante. Quisque gravida tellus at sapien pellentesque imperdiet. Proin lorem augue, accumsan id posuere id, malesuada quis orci. Quisque at felis sit amet velit sagittis commodo. Donec lobortis aliquet risus, ut rutrum felis iaculis vitae.

Aliquam a neque a lectus volutpat mattis ac placerat nunc. Suspendisse sed quam tortor. Maecenas congue pellentesque ligula, quis posuere magna ultricies at. Sed ut est ligula. Sed non nisl ipsum. In et neque leo. Mauris orci nulla, faucibus at ultricies et, semper vel ipsum. Nulla vestibulum aliquet orci, eu ornare neque eleifend sed. Etiam ac laoreet mauris.

Aliquam erat volutpat. Ut dapibus fermentum arcu, eget faucibus dui mollis eget. Vivamus ac malesuada urna. Aenean risus libero, elementum sed blandit et, dignissim sed massa. Etiam ut dolor eget odio tempor volutpat ut ut orci. In ac est a mi rutrum convallis eget et tellus. Vivamus vitae metus arcu, nec facilisis risus. Aenean ut luctus tortor. Curabitur accumsan porta dolor ac pulvinar. Cras quis orci nec quam bibendum condimentum. Curabitur dictum metus id metus sollicitudin vel suscipit justo sodales. Praesent non vestibulum arcu. Nullam lorem diam, accumsan at viverra nec, rhoncus at sapien. Integer hendrerit, massa condimentum eleifend interdum, odio sapien tristique nisl, vel pulvinar erat eros bibendum augue.

Aenean vitae faucibus ipsum. Donec pharetra turpis et turpis commodo eu mollis odio ultrices. Maecenas eget odio leo, non varius massa. Duis tristique elit nibh. Nullam fermentum elit vitae sem hendrerit molestie. Pellentesque at diam erat. Integer ut est purus. Etiam ullamcorper fringilla metus et vulputate. Praesent facilisis, est quis adipiscing congue, eros nisl vehicula nisl, nec laoreet nunc est eget lectus. Duis a consectetur diam.

Pellentesque ut tellus ac libero gravida porttitor eu in risus. Nulla eget quam nisl. Maecenas sodales aliquam neque, vitae egestas neque varius non. Suspendisse eget enim velit, vel egestas purus. Donec libero urna, semper in pharetra sit amet, convallis id risus. Quisque leo mi, mattis id adipiscing quis, sollicitudin varius urna. Aliquam elementum facilisis nibh, a pretium nunc lacinia eget. Aliquam turpis tortor, posuere non euismod nec, hendrerit non nunc. Praesent nisi leo, accumsan id varius sit amet, vehicula a nibh. Proin sollicitudin malesuada leo vel rhoncus. Pellentesque nec nisi vitae enim auctor pellentesque sed eu velit. Pellentesque facilisis dolor et lacus ultrices sed vestibulum arcu cursus. Praesent luctus, leo vel placerat cursus, nibh diam tempus enim, a varius quam turpis et massa. Nulla facilisi. Mauris faucibus tellus ultricies orci dapibus egestas. Morbi vel nisi lacinia leo bibendum fermentum.

Nullam tincidunt nunc ac metus tincidunt sit amet sagittis nisi ultricies. Nunc sit amet tristique mi. Phasellus eu ipsum in erat imperdiet lacinia bibendum consectetur sapien. Sed tincidunt sem eu nulla porta tempor. Aliquam volutpat, felis a mollis ultricies, enim arcu vulputate leo, a tristique neque augue at sapien. Nulla feugiat ante fringilla quam auctor rutrum interdum mauris rhoncus. Nunc pretium odio eget dolor pulvinar consequat.

Integer nisi massa, tincidunt eget bibendum sed, cursus eu ante. Cras eu eros dolor. In facilisis cursus nibh quis congue. Duis et lacus felis. Morbi tempus eros et elit laoreet congue. Donec sodales magna id massa ornare dignissim. Ut et dui at elit eleifend porttitor. In eleifend libero sit amet dui venenatis eu ultricies diam euismod. Morbi elementum nibh et enim cursus vitae consectetur libero egestas. Sed tristique, lacus at tincidunt blandit, dolor purus commodo enim, eu tempus nisl nibh ac nulla. Nam venenatis lobortis massa pharetra egestas. Ut auctor ornare tempor. Nulla ut dolor a arcu pellentesque laoreet.

Nulla sem elit, lacinia id posuere nec, rutrum quis erat. Morbi sit amet feugiat purus. Nam ut massa sit amet dolor blandit tempor nec vel sapien. Curabitur hendrerit purus nec mi tempus nec pellentesque arcu ullamcorper. Curabitur enim felis, sagittis id accumsan et, adipiscing id nisl. Aenean nec mi sit amet massa tincidunt porttitor ut sit amet mi. Ut ac mi erat, quis porta nulla. Aenean et augue lacus, tristique accumsan nibh. Suspendisse sit amet tortor elit.

Aliquam condimentum urna vitae risus pharetra eleifend. Mauris id quam in diam ornare accumsan eget et felis. Aliquam ornare, dolor eu molestie viverra, nibh neque vulputate felis, non ultricies quam leo sed ligula. Nullam consequat ligula eget turpis aliquet vestibulum. Nullam vel est iaculis diam auctor cursus. Praesent vel justo commodo tellus gravida imperdiet vitae sed ipsum. Vestibulum vitae lectus in dolor porttitor varius. Phasellus sem enim, ultricies vitae blandit eu, mattis at nibh. Vestibulum eget sagittis mi. Nullam in massa ut risus varius fringilla. Phasellus porta iaculis massa, ut interdum magna mollis et. Donec facilisis, augue sed gravida ullamcorper, sapien nibh gravida ipsum, et laoreet mauris tellus vel risus. Aliquam ultrices hendrerit ipsum at cursus. Sed elit nisi, tristique eu pellentesque ut, aliquam semper justo.

Maecenas eleifend lorem et nunc posuere et iaculis leo gravida. Nullam odio sem, convallis et commodo sed, scelerisque in enim. Nunc arcu erat, vestibulum et facilisis porta, eleifend id ipsum. Proin rhoncus ipsum eu mi volutpat eu posuere justo placerat. Vivamus hendrerit ante a nibh congue eu gravida sapien sagittis. Duis porta vestibulum purus, ac porta risus sagittis vitae. Etiam eu felis metus.

Nulla non ipsum nibh, non auctor turpis. Proin adipiscing, eros id laoreet vehicula, tellus sem accumsan arcu, vitae semper orci eros ac mauris. Etiam rhoncus neque ac leo commodo non congue velit hendrerit. Curabitur pharetra bibendum accumsan. Pellentesque semper mattis lacus in ornare. Nullam vestibulum urna in metus ultricies aliquet. Nulla pretium malesuada quam, vel venenatis orci dapibus tempus. Aenean convallis iaculis velit. Integer eget placerat nunc. Nullam posuere sodales nisi.

Nulla tincidunt ornare ultrices. Aliquam lobortis orci eu quam imperdiet pretium. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; In vitae urna justo. Sed pretium urna egestas libero pulvinar quis gravida erat vestibulum. Sed pellentesque ullamcorper blandit. Nullam pretium tempus auctor. Nunc eget ligula et nisl posuere porta. Sed velit odio, posuere vel semper sit amet, viverra id elit. In placerat placerat arcu at tincidunt. Nulla sagittis pulvinar tincidunt. Donec feugiat molestie auctor. Duis cursus augue non mauris elementum rutrum.

Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed tempus luctus sem, quis dignissim nulla elementum vel. Praesent consectetur ullamcorper mi in imperdiet. Vivamus facilisis vestibulum fermentum. Quisque lorem odio, venenatis nec rutrum vel, posuere ac nisl. Phasellus eros mi, sagittis at vehicula vitae, ullamcorper in velit. Etiam vitae tellus at neque tempor consectetur quis quis est. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Cras ultricies interdum urna quis congue. Nullam adipiscing mattis turpis, a ultrices erat rhoncus ut. Phasellus elit libero, sagittis a malesuada ut, ultrices a enim. Maecenas sit amet nibh massa.

Proin consequat, augue ac tristique placerat, est orci consectetur ante, eu pretium lectus velit sed dui. Nullam sit amet justo odio. Suspendisse scelerisque, felis at pretium mollis, diam nibh pulvinar lorem, a malesuada felis nisi nec turpis. Aliquam erat volutpat. Aliquam tempor aliquet mauris vel sollicitudin. Proin aliquet porta felis, ut eleifend velit pharetra nec. Aliquam semper dignissim orci id malesuada. Cras leo mi, feugiat non fringilla dignissim, adipiscing non arcu. Praesent id urna non tellus auctor aliquet. Aliquam et orci eget velit porttitor consectetur. Sed sit amet nisi quis purus congue fermentum quis quis lacus. Curabitur arcu orci, sollicitudin et ultricies in, congue sed dolor. Pellentesque turpis urna, condimentum non elementum et, congue hendrerit risus. Nulla facilisi. Aenean id est sed augue scelerisque pulvinar nec et mi. 
